Traceback (most recent call last):
  File "test.py", line 1, in <module>
    pls
NameError: name 'pls' is not defined
